### ISSUE TITLE
add flag to minify the service-worker.js

### ISSUE THREAD

**Issue by alexnoise79** [GoogleChromeLabs/sw-precache#326]
HI all,

i think shuold be good to put a flag to minify the service-worker.js file.

sw-precache [--min] --root=dist --verbose --config=sw-precache-config.js

i don't know if is even possible to uglify.

Thank you

**Comment by jasan-s** [comment]
add this to the end of build script code : `&& uglifyjs build/service-worker.js -o build/service-worker.js`

**Comment by alexnoise79** [comment]
It Works!

Thanks, i suggest to add this into the documentation ;)
