### ISSUE TITLE
caching google oauth

### ISSUE THREAD

**Issue by SergeyShablenko** [GoogleChromeLabs/sw-precache#334]
I\`m writing single paged app using react and node as back-end. I have a trouble with google oauth and sw-precache. I don\`t know how to explain what i have properly, but i\`ll try.

OAuth is written with `PassportJs` and `passport-google-oauth`, so i have 2 end-points to serve OAuth and everything works fine untill i enable sw-precache. It will send me index.html instead of redirecting to google auth page.

Any ideas how to fix that?

**Comment by jeffposnick** [comment]
It sounds like you have `navigateFallback` enabled. There's a whitelist configurable via [`https://github.com/GoogleChromeLabs/sw-precache#navigatefallbackwhitelist-arrayregexp`](https://github.com/GoogleChromeLabs/sw-precache#navigatefallbackwhitelist-arrayregexp) that allows you to opt-in certain URLs to this behavior.

It sounds like you want more of a blacklist than a whitelist, so you could use a negative `RegExp`.

Alternatively, you could migrate to Workbox, which does support both white and blacklists for its equivalent `navigateFallback` behavior: https://developers.google.com/web/tools/workbox/
