### ISSUE TITLE
Because of dep on old update-notifier, unable to use with node 8 and engine-strict=true

### ISSUE THREAD

**Issue by markFromMST** [GoogleChromeLabs/sw-precache#339]
Currently there is a dep on update-notifier of 1.0.3, which then pulls in an old version of latest-version (2.0.0) which then pulls in an old version of package-json (2.4.0) which then pulls in an old version of got (5.7.1) which then only allows:

"engines": {
    "node": ">=0.10.0 <7"
  },

the latest version of got allows:

  "engines": {
    "node": ">=4"
  },

**Comment by markFromMST** [comment]
I cloned the repo, updated the dep and the unit tests pass.  Strangely lint does not, but that is not related.

**Comment by jeffposnick** [comment]
Thanks for investigating, @markFromMST! If you can put together a pull request that contains the updates to `package.json`, I'd be happy to review.

**Comment by cdanielsen** [comment]
Should have consulted the issues first, but I made https://github.com/GoogleChromeLabs/sw-precache/pull/344 independently for this exact issue
