### ISSUE TITLE
Add option: prefixUri

### ISSUE THREAD

**Issue by retyui** [GoogleChromeLabs/sw-precache#347]
my repo app has next struct:
```
├── css
│   └── styles.css
├── js
│   └── questions.js
├── img
│   └── 33.png
├── index.html
```
But on the server it is stored in a separate folder
`http://exmaple.com/user/project/`
And I have to add this folder prefix `/user/project/` each time : (

**Comment by jeffposnick** [comment]
You should be able to use the [`stripPrefixMulti` option](https://github.com/GoogleChromeLabs/sw-precache#stripprefixmulti-object):

```js
stripPrefixMulti: {
  '': '/user/project/'
}
```

(`''` means "strip the empty string" and replace it with the prefix you want.)
