### ISSUE TITLE
skipWaiting false and a refresh button

### ISSUE THREAD

**Issue by jliebrand** [GoogleChromeLabs/sw-precache#364]
Hi there,

I have a SPA with dynamic bundles, so long story short: I need to use skipWaiting=false to ensure caches aren't removed from underneath the current app. This works fine, as long as the user closes the tab every now and then.

I'd like to add a common "The app has updated, please reload" button, but I can't seem to find what message to post to the generated sw for it to call self.skipWaiting ?  In fact, looking at the code, it doesn't appear that's in there?

Does that mean that we won't be able to have the user refresh with skipWaiting=false in the config?

**Comment by jliebrand** [comment]
Ah ... I think I might be able to cobble something together using importScripts...

But consider this a feature request: having sw-precache is great, since you dont need to write a sw yourself. But if it doesn't communicate with the client, it falls a little short. It would be great if the default gereated sw would post some messages to the client (like 'new-content-available' or 'please-reload')... And that it would support some standard messages coming in as well (like 'skip-waiting') to force it to skip waiting...

**Comment by jeffposnick** [comment]
So, it's not likely that anything like that will be added to `sw-precache`. The team's [focus](https://github.com/GoogleChromeLabs/sw-precache#support) has been on enhancing the successor, [Workbox](https://developers.google.com/web/tools/workbox/), for a while now.

We have a [guide in the Workbox](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users) docs for handling what you describe, and some of it would also apply to `sw-precache`.
