### ISSUE TITLE
SW precaching static assets delaying onload?

### ISSUE THREAD

**Issue by samarpanda** [GoogleChromeLabs/sw-precache#366]
### SW operates in a different thread i.e not the main thread
>`All resources that are precached will be fetched by a service worker running in a separate thread as soon as the service worker is installed. You should be judicious in what you list in the dynamicUrlToDependencies and staticFileGlobs options, since listing files that are non-essential (large images that are not shown on every page, for instance) will result in browsers downloading more data than is strictly necessary.`

How about downloading precache assets. Do they are dependent on main thread that delays the on load event? Seems like yes.

![screen_shot_2018-08-14_at_9_52_50_am](https://user-images.githubusercontent.com/802163/44071948-9e02dd26-9fa9-11e8-9c93-4aecc9fb0c28.png)

**Comment by samarpanda** [comment]
We were pre-caching all static assets earlier. Expecting these downloads to happen in the background.  But seems its not. Anyways to trigger these download in the background so it doesn't impact the main thread, especially the on load event?

**Comment by jeffposnick** [comment]
Please see https://developers.google.com/web/fundamentals/primers/service-workers/registration

The best practice is generally something like

```js
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function() {
    navigator.serviceWorker.register('/service-worker.js');
  });
}
```

**Comment by samarpanda** [comment]
@jeffposnick ok, got you need to initiate ServiceWorker after `onload` event. Wondering on couple of points:

1. There are lot of files. Is it advised to do all of them together or in junks using [request Idle callback](https://developers.google.com/web/updates/2015/08/using-requestidlecallback)?
1. On a completely different approach can we move it to runtime caching. So, we cache file on demand, basically disabling most of the pre-caching(Which is triggered after ServiceWorker is installed)

**Comment by jeffposnick** [comment]
Regarding the preache payload size, there are some thoughts at https://stackoverflow.com/questions/51595558/recommended-precache-payload-size/51595559

In general, it's more efficient to use precaching when possible, since you have an efficient update cycle, and you can ensure that all required files are downloaded as part of an atomic `install` step.
